server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?autoReconnect=true
    username: root
    password: 
    hikari: 
      maximumPoolSize: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
    
    
    
management: 
  endpoints: 
    web: 
      exposure: 
        include: health,info,metrics,prometheus
